# Generated by Django 5.1.7 on 2025-04-14 14:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='guestuser',
            name='guest_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
