# Generated by Django 5.1.7 on 2025-04-14 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_guestuser_id_alter_guestuser_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='guest_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=48, primary_key=True, serialize=False),
        ),
    ]
