# Generated by Django 5.1.7 on 2025-04-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_guestuser_id_alter_guestuser_guest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=112, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestuser',
            name='guest_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
