services:
    web:
        build: .
        volumes:
            - .:/app
        ports:
            - '8000:8000'

    nginx:
        build: ./nginx
        ports:
            - '443:443'
        depends_on:
            - web
