services:
    web:
        image: amarher/backend-web:latest
        depends_on:
            - db
        # volumes:
        #     - .:/app
        ports:
            - '8000:8000'
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.web.rule=Host(`api.axmh.tech`)'
            - 'traefik.http.routers.web.tls=true'
            - 'traefik.http.routers.web.tls.certresolver=myresolver'
        env_file:
            - .env

    db:
        image: postgres:latest
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - '5432:5432'
    traefik:
        image: traefik:v2.10
        depends_on:
            - web
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - './letsencrypt:/letsencrypt'
        command:
            - '--api.insecure=true'
            - '--providers.docker=true'
            - '--providers.docker.exposedbydefault=false'
            - '--entrypoints.web.address=:80'
            - '--entrypoints.websecure.address=:443'
            - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
            - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
            - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
            - '--certificatesresolvers.myresolver.acme.email=${CERT_EMAIL}'
            - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
        env_file:
            - .env

volumes:
    db_data:
