# Generated by Django 5.1.7 on 2025-04-15 09:32

import compression.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_guestuser_id_alter_guestuser_guest_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('temp', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=compression.models.get_upload_path)),
                ('quality', models.IntegerField(default=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.guestuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
