# Generated by Django 5.1.7 on 2025-03-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compressedimage',
            old_name='compressed_file',
            new_name='compressed_image',
        ),
        migrations.RenameField(
            model_name='compressedimage',
            old_name='original_file',
            new_name='original_image',
        ),
    ]
