# Generated by Django 5.1.7 on 2025-04-14 08:36

import compression.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedimage',
            name='perm_image',
            field=models.ImageField(blank=True, null=True, storage=compression.models.PermStorage, upload_to=compression.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='compressedimage',
            name='temp_image',
            field=models.ImageField(blank=True, null=True, upload_to=compression.models.get_upload_path),
        ),
    ]
