# Generated by Django 5.1.7 on 2025-04-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedimage',
            name='temp',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
