# Generated by Django 5.1.7 on 2025-04-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0002_alter_compressedimage_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
