# Generated by Django 5.1.7 on 2025-04-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('compression', '0002_alter_compressedimage_perm_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressedimage',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guestuser'),
        ),
    ]
