# Generated by Django 5.1.7 on 2025-03-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0002_rename_compressed_file_compressedimage_compressed_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedimage',
            name='compressed_image',
            field=models.ImageField(upload_to='compressed_images/'),
        ),
        migrations.AlterField(
            model_name='compressedimage',
            name='original_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
