# Generated by Django 5.1.7 on 2025-03-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0002_image_user_video_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompressionSettings',
            new_name='CompressionSetting',
        ),
    ]
