# Generated by Django 5.1.7 on 2025-04-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_guestuser_guest_id'),
        ('compression', '0003_compressedimage_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedimage',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.guestuser'),
        ),
    ]
