# Generated by Django 5.1.7 on 2025-04-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0003_alter_compressedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedimage',
            name='temp',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
