# Generated by Django 5.1.7 on 2025-04-04 18:45

import compression.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0004_alter_compressedimage_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedimage',
            name='image',
            field=models.ImageField(upload_to=compression.models.get_upload_path),
        ),
    ]
