# Generated by Django 5.1.7 on 2025-04-15 14:37

import compression.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0005_alter_compressedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=compression.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='compressedimage',
            name='temp',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
