# Generated by Django 5.1.7 on 2025-05-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0006_alter_compressedimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressedimage',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
