# Generated by Django 5.1.7 on 2025-05-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0007_compressedimage_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressedimage',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
