# Generated by Django 5.1.7 on 2025-05-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression', '0008_alter_compressedimage_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressedimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
